import type { EnemyKind } from "./entities";

/**
 * The in-game bestiary. Entries unlock the first time your Friend sees each creature, and keep
 * a kill count and any guardian you have slain. Session only, like the stash and codex.
 */
export type BestiaryKind = Exclude<EnemyKind, "target">;
export type BestiaryGroup = "Crypt" | "Signal" | "Flesh" | "Frost" | "Ember" | "Rot" | "Sunken" | "Clock" | "Mirror" | "Void" | "Elite" | "Boss";
export type LoreEntry = Readonly<{ name: string; group: BestiaryGroup; lore: string; attacks: readonly string[]; found: string }>;

export const LORE: Readonly<Record<BestiaryKind, LoreEntry>> = {
  cursed: { name: "Cursed Friend", group: "Crypt", found: "Everywhere, from depth 1",
    lore: "A Friend that went down the stairs and never came back up. It still remembers how to run.",
    attacks: ["Rushes you and swings after a short red wind-up."] },
  crawler: { name: "Void Crawler", group: "Crypt", found: "Depths 1–7",
    lore: "Many-legged and eyeless. It hears your footsteps through the stone.",
    attacks: ["Keeps its distance and spits aimed void orbs: one, then two, then three as you go deeper."] },
  wisp: { name: "Choir Wisp", group: "Crypt", found: "Depths 1–3, 6, the Void",
    lore: "A lost voice from the crypt choir, still singing the one note it knows.",
    attacks: ["Floats at range and releases a full ring of bullets."] },
  bomber: { name: "Grave Bomber", group: "Crypt", found: "Depths 1–2, 4, 9, the Void",
    lore: "Packed with grave-salt and bad intentions. It only ever gets one hug.",
    attacks: ["Sprints at you, lights its fuse and explodes.", "Bursts when killed, too. Kill it from range."] },
  gunner: { name: "Bone Gunner", group: "Crypt", found: "Depths 2–3, 5, 8, the Void",
    lore: "Its rifle is a femur. Its ammunition is also a femur.",
    attacks: ["Aims, then fires a shotgun spread of pellets."] },
  lancer: { name: "Bone Lancer", group: "Crypt", found: "Depths 2–3, the Void",
    lore: "A crypt knight who still keeps the old drills, and a very long spear.",
    attacks: ["Marks a white line with its spear, then skewers straight down it."] },
  wraith: { name: "Grave Wraith", group: "Crypt", found: "Depths 3, 8, the Void",
    lore: "You won't see it. You'll see the shimmer where it was a moment ago.",
    attacks: ["Nearly invisible while it stalks you.", "Reveals itself, flashes red, then lunges."] },
  hexer: { name: "Hex Priest", group: "Crypt", found: "Depths 3, 6, 9, the Void",
    lore: "It prays to something at the bottom of the stairs, and something answers.",
    attacks: ["Brands the floor under you with three curse circles.", "Every third prayer mends its most wounded ally."] },
  drone: { name: "Static Drone", group: "Signal", found: "Depths 4–6, 9, the Void",
    lore: "Still running its patrol from a network nobody remembers building.",
    attacks: ["Strafes around you, then fires a quick burst of three or more rounds."] },
  mite: { name: "Signal Mite", group: "Signal", found: "Depths 4–6, the Void",
    lore: "Tiny, fast, and never alone.",
    attacks: ["Swarms in packs of four and lunges after a brief tell."] },
  sniper: { name: "Relay Sniper", group: "Signal", found: "Depths 4–6, the Void",
    lore: "It waits a long time for one shot. It rarely needs a second.",
    attacks: ["Tracks you with a thin laser sight.", "Locks on, then fires one very fast round down the line."] },
  turret: { name: "Relay Turret", group: "Signal", found: "Depths 5–6, the Void",
    lore: "Bolted to the floor, still guarding a door that no longer exists.",
    attacks: ["Spins a two- or three-armed bullet spiral, then cools down."] },
  hive: { name: "Hive Mother", group: "Signal", found: "Depths 5–6, 8, the Void",
    lore: "Where Signal Mites come from. Please do not look inside.",
    attacks: ["Rooted in place; births pairs of Signal Mites.", "Pulses slow rings of spores."] },
  bloodling: { name: "Bloodling", group: "Flesh", found: "Depths 7–9, the Void",
    lore: "A clot that learned to walk. Cut it and it becomes two clots that walk.",
    attacks: ["Rushes and bites.", "Splits into two smaller Bloodlings when killed."] },
  spitter: { name: "Maw Spitter", group: "Flesh", found: "Depths 7–9, the Void",
    lore: "All mouth. Aims badly on purpose.",
    attacks: ["Lobs a glob at a marked spot; it bursts into a ring of bullets where it lands."] },
  brute: { name: "Flesh Brute", group: "Flesh", found: "Depths 7–9, the Void",
    lore: "Slow to start, impossible to stop. Knockback barely moves it.",
    attacks: ["Pounds the ground in a wide red circle.", "The pound throws out a ring of gore."] },
  eyestalk: { name: "Eye Stalk", group: "Flesh", found: "Depths 8–9, the Void",
    lore: "It has been watching you since the first floor. It finally has a good angle.",
    attacks: ["Marks a line with its gaze, then fires a stream of needles down it."] },
  shade: { name: "Null Shade", group: "Void", found: "Depths 19, 25, 28–30 and the endless void",
    lore: "A shadow with no Friend left to cast it.",
    attacks: ["Fires needle spreads while it follows you.", "Vanishes and blinks in beside you with a bullet ring."] },
  prism: { name: "Void Prism", group: "Void", found: "Depths 24, 27, 28–30 and the endless void",
    lore: "A shard of whatever the Void was before it broke.",
    attacks: ["Spits rotating crosses of bullets.", "Charges, then sweeps a long laser across the room."] },
  frostmoth: { name: "Frost Moth", group: "Frost", found: "The Frozen Archive (depths 10–12), 20, 28",
    lore: "It ate the pages of every book in the Archive. Now it is always cold.",
    attacks: ["Flutters at range and throws a fan of three frost needles that slow you."] },
  rimeknight: { name: "Rime Knight", group: "Frost", found: "The Frozen Archive, 21, 30",
    lore: "It guards the stacks. It has forgotten what is on them.",
    attacks: ["Marks a line, then charges down it.", "Leaves a trail of frost that hurts and slows."] },
  cinderimp: { name: "Cinder Imp", group: "Ember", found: "The Ember Forge (depths 13–15), 24, 28",
    lore: "A spark from the forge that learned to hop, and then to throw.",
    attacks: ["Lobs fireballs that leave burning pools where they land.", "Two burst out of every Slag Golem."] },
  slaggolem: { name: "Slag Golem", group: "Ember", found: "The Ember Forge, 23, 30",
    lore: "Poured, cooled, cracked and walking. It is still warm inside.",
    attacks: ["Stomps a marked circle and throws out a ring of molten slag.", "Breaks into two Cinder Imps when it dies."] },
  sporeling: { name: "Sporeling", group: "Rot", found: "The Rot Garden (depths 16–18), 26",
    lore: "It grew out of a Friend. It would like to grow out of you.",
    attacks: ["Drops a lingering spore cloud where you stand.", "Spits a fan of slow seeds."] },
  thorn: { name: "Thorn Crawler", group: "Rot", found: "The Rot Garden, 28",
    lore: "The ground ripples, and then it is not the ground anymore.",
    attacks: ["Burrows toward you, out of reach.", "Erupts under a marked circle in a burst of eight thorns, then sits exposed."] },
  belldiver: { name: "Bell Diver", group: "Sunken", found: "The Sunken Choir (depths 19–21), 27, 29",
    lore: "It still rings the drowned bell, three fathoms down.",
    attacks: ["Dives out of reach and resurfaces near you.", "Tolls: a marked ring around it, then a ring of bullets."] },
  eel: { name: "Choir Eel", group: "Sunken", found: "The Sunken Choir, 25",
    lore: "It remembers the hymn. It sings it slightly wrong.",
    attacks: ["Weaves at range and sings a wavering stream of bullets."] },
  cog: { name: "Cog Sentry", group: "Clock", found: "The Clockwork Tomb (depths 22–24), 29",
    lore: "It turns because it was told to turn. Nobody told it to stop.",
    attacks: ["Rooted. Spins three arms of gear-shot, reversing direction every few seconds."] },
  pendulum: { name: "Pendulum Knight", group: "Clock", found: "The Clockwork Tomb, 27",
    lore: "Tick. Tock. Tick. It has never once been late.",
    attacks: ["Closes in and swings twice, left then right, each arc marked first."] },
  shardling: { name: "Glass Shardling", group: "Mirror", found: "The Mirror Halls (depths 25–27), 29",
    lore: "A splinter of a broken mirror that still shows a face.",
    attacks: ["Swarms you with quick swipes.", "Shatters into six shards when it dies: kill it at range."] },
  mirror: { name: "Mirror Sentinel", group: "Mirror", found: "The Mirror Halls, 30",
    lore: "Stand in front of it long enough and it stops showing you.",
    attacks: ["Throws a fan of glass.", "Bolts that hit its mirror face fly straight back at you. Strike it from the side, or up close."] },
  seraph: { name: "Null Seraph", group: "Void", found: "The Null Throne (depths 28–30) and the endless void",
    lore: "It sings for the First Friend. Nobody else can hear it.",
    attacks: ["Lets down curtains of void light with a single gap.", "Or a slow crown of sixteen needles."] },
  goblin: { name: "Loot Goblin", group: "Elite", found: "Any combat room, rarely",
    lore: "It has your loot. Technically it has everyone's loot.",
    attacks: ["Harmless. Flees, dropping RF coins, and escapes through a rift after 14 seconds."] },
  corrupted: { name: "Corrupted Friend", group: "Elite", found: "Elite rooms, gates and ambushes",
    lore: "Your own Friend, crimson and wrong. It knows every move you know.",
    attacks: ["Charges down a marked line.", "Slams the ground around it.", "Carries 1–3 modifiers."] },
  warden: { name: "Dungeon Warden", group: "Boss", found: "Depths 3 and 6 (Warden of the Deep)",
    lore: "The jailer of the upper crypts. Nobody has ever seen its key.",
    attacks: ["Slam, cone sweep and a charge that stuns it against walls.", "Chains: three whirling arms of bullets.", "Quake: a fissure of slams marching toward you.", "Summons, bullet rings and (in the deep) a blink."] },
  beast: { name: "The Rare Beast", group: "Boss", found: "Depth 9",
    lore: "The thing at the bottom of the Hollow Deep. Every eye it opens is one more reason to leave.",
    attacks: ["Claws, spirals, stomps and charges.", "Eyes: every eye fires a needle in turn.", "Curtain: a wall of bullets with one gap.", "Phase 3: cursed pools and a sweeping beam."] },
  archivist: { name: "The Archivist", group: "Boss", found: "Depth 12",
    lore: "It keeps every Friend the dungeon has ever taken, filed and frozen. It has a shelf ready for yours.",
    attacks: ["Index: three widening fans of frost needles.", "Catalog: four frozen lines across your path.", "Freeze: a slowing slam; calls frozen husks from the shelves.", "Phase 2: a blizzard spiral."] },
  forgemaster: { name: "The Forgemaster", group: "Boss", found: "Depth 15",
    lore: "Every chain in the dungeon came off its anvil. It is making one more.",
    attacks: ["Hammer: a slam that leaves molten slag behind.", "Anvils: five marked strikes around you.", "A fountain of sparks and a charge that stuns it against walls.", "Phase 2: double rings of fire."] },
  bloom: { name: "The Mother Bloom", group: "Boss", found: "Depth 18",
    lore: "The garden's heart, rooted in something that used to be a Friend.",
    attacks: ["Petals: a rotating spiral of five arms (seven at the end).", "Spores that linger and vines that lash out in marked lines.", "Seedlings: Sporelings and Thorn Crawlers.", "Phase 2: a crown of slow pollen needles."] },
  cantor: { name: "The Drowned Cantor", group: "Boss", found: "Depth 21",
    lore: "It led the choir the day the water came in, and it never stopped singing.",
    attacks: ["Tide: a wall of water with one gap to swim through.", "Toll: a marked ring and a bullet ring.", "Undertow: drags you in, then a ring breaks outward.", "Hymn: two wavering streams. Phase 2: it sinks and resurfaces."] },
  hourengine: { name: "The Hour Engine", group: "Boss", found: "Depth 24",
    lore: "The clock the whole tomb was built around. It is counting down to something.",
    attacks: ["Hands: long beams that sweep around the room.", "Tick: twelve marks go off around it in turn.", "Gears that burst into rings.", "From phase 2 its gears shed a slow spiral; phase 3 chimes in rings."] },
  reflection: { name: "The Reflection", group: "Boss", found: "Depth 27",
    lore: "Your Friend, as the mirror remembers it. It has been practicing your moves.",
    attacks: ["Echo: your own bolt style, turned back on you.", "Your family's signature ability, cast against you.", "Steps to your mirror position across the room and throws glass.", "Phase 2: two false reflections that break in a few hits."] },
  firstfriend: { name: "The First Friend", group: "Boss", found: "Depth 30, the bottom of the Descent",
    lore: "The first Rare Friend ever to take the stairs. It has been waiting down here for company.",
    attacks: ["Genesis: alternating rings of white and gold.", "Cross: sweeping beams, then more of them.", "Mint: a spiral of coins and light; calls creatures from every act.", "Phase 2 curtains; phase 3 judgement strikes around you."] },
  unminted: { name: "The Unminted", group: "Boss", found: "Behind the Void's worst gambles",
    lore: "A Friend that was never minted, wearing your silhouette because it has none of its own.",
    attacks: ["Bullet rings, needle fans and blinks.", "Cursed pools, and Starfall: a spiral of void stars around you."] },
};

export const BESTIARY_ORDER = Object.keys(LORE) as BestiaryKind[];
