import type { EnemyKind } from "./entities";

/**
 * The in-game bestiary. Entries unlock the first time your Friend sees each creature, and keep
 * a kill count and any guardian you have slain. Session only, like the stash and codex.
 */
export type BestiaryKind = Exclude<EnemyKind, "target">;
export type BestiaryGroup = "Crypt" | "Signal" | "Flesh" | "Void" | "Elite" | "Boss";
export type LoreEntry = Readonly<{ name: string; group: BestiaryGroup; lore: string; attacks: readonly string[]; found: string }>;

export const LORE: Readonly<Record<BestiaryKind, LoreEntry>> = {
  cursed: { name: "Cursed Friend", group: "Crypt", found: "Everywhere, from depth 1",
    lore: "A Friend that went down the stairs and never came back up. It still remembers how to run.",
    attacks: ["Rushes you and swings after a short red wind-up."] },
  crawler: { name: "Void Crawler", group: "Crypt", found: "Depths 1–7",
    lore: "Many-legged and eyeless. It hears your footsteps through the stone.",
    attacks: ["Keeps its distance and spits aimed void orbs: one, then two, then three as you go deeper."] },
  wisp: { name: "Choir Wisp", group: "Crypt", found: "Depths 1–3, 6, the Void",
    lore: "A lost voice from the crypt choir, still singing the one note it knows.",
    attacks: ["Floats at range and releases a full ring of bullets."] },
  bomber: { name: "Grave Bomber", group: "Crypt", found: "Depths 1–2, 4, 9, the Void",
    lore: "Packed with grave-salt and bad intentions. It only ever gets one hug.",
    attacks: ["Sprints at you, lights its fuse and explodes.", "Bursts when killed, too. Kill it from range."] },
  gunner: { name: "Bone Gunner", group: "Crypt", found: "Depths 2–3, 5, 8, the Void",
    lore: "Its rifle is a femur. Its ammunition is also a femur.",
    attacks: ["Aims, then fires a shotgun spread of pellets."] },
  lancer: { name: "Bone Lancer", group: "Crypt", found: "Depths 2–3, the Void",
    lore: "A crypt knight who still keeps the old drills, and a very long spear.",
    attacks: ["Marks a white line with its spear, then skewers straight down it."] },
  wraith: { name: "Grave Wraith", group: "Crypt", found: "Depths 3, 8, the Void",
    lore: "You won't see it. You'll see the shimmer where it was a moment ago.",
    attacks: ["Nearly invisible while it stalks you.", "Reveals itself, flashes red, then lunges."] },
  hexer: { name: "Hex Priest", group: "Crypt", found: "Depths 3, 6, 9, the Void",
    lore: "It prays to something at the bottom of the stairs, and something answers.",
    attacks: ["Brands the floor under you with three curse circles.", "Every third prayer mends its most wounded ally."] },
  drone: { name: "Static Drone", group: "Signal", found: "Depths 4–6, 9, the Void",
    lore: "Still running its patrol from a network nobody remembers building.",
    attacks: ["Strafes around you, then fires a quick burst of three or more rounds."] },
  mite: { name: "Signal Mite", group: "Signal", found: "Depths 4–6, the Void",
    lore: "Tiny, fast, and never alone.",
    attacks: ["Swarms in packs of four and lunges after a brief tell."] },
  sniper: { name: "Relay Sniper", group: "Signal", found: "Depths 4–6, the Void",
    lore: "It waits a long time for one shot. It rarely needs a second.",
    attacks: ["Tracks you with a thin laser sight.", "Locks on, then fires one very fast round down the line."] },
  turret: { name: "Relay Turret", group: "Signal", found: "Depths 5–6, the Void",
    lore: "Bolted to the floor, still guarding a door that no longer exists.",
    attacks: ["Spins a two- or three-armed bullet spiral, then cools down."] },
  hive: { name: "Hive Mother", group: "Signal", found: "Depths 5–6, 8, the Void",
    lore: "Where Signal Mites come from. Please do not look inside.",
    attacks: ["Rooted in place; births pairs of Signal Mites.", "Pulses slow rings of spores."] },
  bloodling: { name: "Bloodling", group: "Flesh", found: "Depths 7–9, the Void",
    lore: "A clot that learned to walk. Cut it and it becomes two clots that walk.",
    attacks: ["Rushes and bites.", "Splits into two smaller Bloodlings when killed."] },
  spitter: { name: "Maw Spitter", group: "Flesh", found: "Depths 7–9, the Void",
    lore: "All mouth. Aims badly on purpose.",
    attacks: ["Lobs a glob at a marked spot; it bursts into a ring of bullets where it lands."] },
  brute: { name: "Flesh Brute", group: "Flesh", found: "Depths 7–9, the Void",
    lore: "Slow to start, impossible to stop. Knockback barely moves it.",
    attacks: ["Pounds the ground in a wide red circle.", "The pound throws out a ring of gore."] },
  eyestalk: { name: "Eye Stalk", group: "Flesh", found: "Depths 8–9, the Void",
    lore: "It has been watching you since the first floor. It finally has a good angle.",
    attacks: ["Marks a line with its gaze, then fires a stream of needles down it."] },
  shade: { name: "Null Shade", group: "Void", found: "The Endless Void",
    lore: "A shadow with no Friend left to cast it.",
    attacks: ["Fires needle spreads while it follows you.", "Vanishes and blinks in beside you with a bullet ring."] },
  prism: { name: "Void Prism", group: "Void", found: "The Endless Void",
    lore: "A shard of whatever the Void was before it broke.",
    attacks: ["Spits rotating crosses of bullets.", "Charges, then sweeps a long laser across the room."] },
  goblin: { name: "Loot Goblin", group: "Elite", found: "Any combat room, rarely",
    lore: "It has your loot. Technically it has everyone's loot.",
    attacks: ["Harmless. Flees, dropping RF coins, and escapes through a rift after 14 seconds."] },
  corrupted: { name: "Corrupted Friend", group: "Elite", found: "Elite rooms, gates and ambushes",
    lore: "Your own Friend, crimson and wrong. It knows every move you know.",
    attacks: ["Charges down a marked line.", "Slams the ground around it.", "Carries 1–3 modifiers."] },
  warden: { name: "Dungeon Warden", group: "Boss", found: "Depths 3 and 6 (Warden of the Deep)",
    lore: "The jailer of the upper crypts. Nobody has ever seen its key.",
    attacks: ["Slam, cone sweep and a charge that stuns it against walls.", "Chains: three whirling arms of bullets.", "Quake: a fissure of slams marching toward you.", "Summons, bullet rings and (in the deep) a blink."] },
  beast: { name: "The Rare Beast", group: "Boss", found: "Depth 9",
    lore: "The thing at the bottom. Every eye it opens is one more reason to leave.",
    attacks: ["Claws, spirals, stomps and charges.", "Eyes: every eye fires a needle in turn.", "Curtain: a wall of bullets with one gap.", "Phase 3: cursed pools and a sweeping beam."] },
  unminted: { name: "The Unminted", group: "Boss", found: "Behind the Void's worst gambles",
    lore: "A Friend that was never minted, wearing your silhouette because it has none of its own.",
    attacks: ["Bullet rings, needle fans and blinks.", "Cursed pools, and Starfall: a spiral of void stars around you."] },
};

export const BESTIARY_ORDER = Object.keys(LORE) as BestiaryKind[];
